stages:
  evaluate:
    cmd: python src/evaluate.py
    deps:
    - src/evaluate.py
    - params.yaml
    - data/processed/test.pt
    - models/model.pth
    outs:
    - confusion_matrix.png
    metrics:
    - metrics.json
